### ISSUE TITLE
Multiple Phone Number Bug

### ISSUE THREAD

**Issue by jpwalters** [jpwalters/OpenVBX-Plugin-SMS-Conversation#18]
If you have multiple twilio numbers in the system and a caller sends an sms message to BOTH numbers the conversation plugin will group all messages under the first phone number they messaged which is a bug.  The plugin should differentiate which number a caller messaged.

NOTE: BUG found by @gegere.  Thanks for mentioning the issue.

**Comment by jpwalters** [comment]
The bug fix has been submitted.  I'm just waiting on someone to QA it and verify its fixed before I close this issue.

**Comment by gegere** [comment]
Nice work, I'll test this all later today.
