### ISSUE TITLE
Two Digit Country Code Issue

### ISSUE THREAD

**Issue by bkonia** [jpwalters/OpenVBX-Plugin-SMS-Conversation#27]
Hi James,

Please take a look at the two screen shots, one from the standard SMS Inbox, the other from SMS Conversation. You'll notice in SMS Conversation, the characters preceding the apostrophe have been lost. I presume this is happening because the apostrophe is a UTF-8 character, which the plugin is not handling properly.

![2016-04-27_12-09-43](https://cloud.githubusercontent.com/assets/2266423/14865020/7bb80570-0c71-11e6-8057-d8826f80bf39.png)
![2016-04-27_12-08-45](https://cloud.githubusercontent.com/assets/2266423/14865022/7cd4d172-0c71-11e6-8510-86e6b3a86d0a.png)

**Comment by jpwalters** [comment]
This is another interesting bug.  Unfortunately I can't reproduce it.  

No matter what I do the characters before the apostrophe or single quote always appear for me.  
1. How many digits including the country code does the phone number you're using have?
2. Was this a message you sent or you received?
3. Can you reproduce it on demand?
4. If the contracted word is somewhere other than starting the sentence does the issue occur?

Here's a screen shot of me trying to reproduce it.
![image](https://cloud.githubusercontent.com/assets/4819310/14907580/e39b6ec0-0d98-11e6-8a98-9772089c5493.png)

**Comment by bkonia** [comment]
It's hard to tell from the screen shot, but it looks like you're using regular ASCII apostrophes, not the UTF-8 [right single quotation mark](http://www.fileformat.info/info/unicode/char/2019/index.htm). I'll do some more testing on my end though.

**Comment by bkonia** [comment]
Well, it just happened again and this time, there were no special characters in the message. It dropped the first two characters. To answer your questions:
1. The phone number contained ten digits, but interestingly, both times this happened, it was with a non-US phone number.
2. In both instances, it happened with messages I sent, in response to a message I'd received.
3. Yes, I just tested it again, by sending another reply to the same number, and once again, it dropped the first two characters.

**Comment by jpwalters** [comment]
I just tested with right single quotation marks and still didn't reproduce the issue.  However I don't think that's the problem.  OpenVBX does some weirdness when it saves messages to the database and that make this plugin do some weirdness in order to build a list of which numbers are messaging one another.  

Tell me what country the phone number that you're having issue with is from and I'll purchase one and I bet I'll be able to reproduce the issue.

![image](https://cloud.githubusercontent.com/assets/4819310/14916402/812424b8-0de7-11e6-8ad6-fae6de727c28.png)

**Comment by bkonia** [comment]
Hi James,

Did you see my previous reply? I noted that I experienced the same issue in a message containing no special characters, so I agree with you. This only happens when I send a message to a non-US number. So far, it's happened with country codes 31 and 41.

Also, I just noticed SMS Conversation formats international numbers incorrectly. For example, a number like +41 123456789, displays as +4 (112) 345-6789. The standard SMS Inbox plugin doesn't attempt to format international numbers at all, so the easiest solution would be to do the same. However, if you want to get fancy, Twilio provides a free Lookup API that will take a phone number and country ID and return (among other things) the locally formatted number. The incoming TwiML request provides the country ID, so this should work.

**Comment by jpwalters** [comment]
Yeah ... that's what I thought the issue was.  The way I'm handling the phone number isn't account for multi-digit country codes and therefore its eating part of the message.  I'll work on this shortly and get a fix out to you.

**Comment by jpwalters** [comment]
@bkonia, I believe I've fixed this issue and have just released version1.4.  Please test and let me know if this resolves the problem you are experiencing.

Note: In researching this issue I'm realizing that all phone numbers don't follow the same rules.  For example country codes can be 1 to 4 numbers in length and phones can be 10 - 14 digits.  Therefore currently the plugin supports 12 digits total length phone numbers.  Supporting all possible lengths was going to be too complicated to add today and therefore I'll tackle other lengths and formats when/if they become an issue.

**Comment by bkonia** [comment]
OK, I'll give it a try, but you should really check out the Twilio Lookups
API. As I mentioned, it's free to use and it does all the international
formatting for you. I'm currently using it for another project and it works
great.
ᐧ

**Comment by bkonia** [comment]
And yes, the bug with characters dropping seems to be fixed.
