### ISSUE TITLE
A way to start the sms conversation

### ISSUE THREAD

**Issue by robertoamoreno** [jpwalters/OpenVBX-Plugin-SMS-Conversation#30]
Cannot start the sms conversation from the interface, so you can only see the first reply

**Comment by jpwalters** [comment]
@robertoamoreno,  Thanks for the feature enhancement.  Yes, several people have asked for this as well.  This duplicates issue #14 so we'll close this but keep #14 on the list.  I'm hoping to create this feature soon.
