### ISSUE TITLE
Sending SMS Messages when OpenVBX installed in a Sub Directory

### ISSUE THREAD

**Issue by jpwalters** [jpwalters/OpenVBX-Plugin-SMS-Conversation#8]
**Bug Description:**
If you install OpenVBX in a sub directory (http://domain.com/test/) the plugin will allow you to see incoming sms message but will give you an error when sending sms messages.

**Error Message:**
![image](https://cloud.githubusercontent.com/assets/4819310/14096990/f5099bd0-f53a-11e5-9bdb-f3d6ff1febcd.png)

Thanks @gegere for finding and submitting the fix for this bug!

The bug was also submitted by someone else here:[https://getsatisfaction.com/openvbx/topics/sms-conversation-view-error]

**Comment by gegere** [comment]
@jpwalters The function uses an Ajax call to keep the SMS conversation thread up to date.

This bug has been resolved, but the structure of the default installation will need to be moved back a director to merge my pull request correctly.
https://github.com/jpwalters/OpenVBX-Plugin-SMS-Conversation/pull/6#issuecomment-202698497
